spring.application.name=therapy-connect.platform
spring.datasource.url=jdbc:mysql://localhost:3306/therapy_connect
spring.datasource.username=root
spring.datasource.password=Deikogamer138
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

authorization.jwt.secret=therapyConnectPlatformSecretKeyForJwtTokenGeneration2024
authorization.jwt.expiration.days=7

documentation.application.description=Therapy Connect Platform API
documentation.application.version=1.0.0

server.tomcat.protocol-handler-class-name=org.apache.coyote.http11.Http11Nio2Protocol