# Production profile
spring.datasource.url=jdbc:postgresql://68.155.147.143:5432/therapyconnect_db
spring.datasource.username=postgres
spring.datasource.password=Deikogamer138

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

server.port=${PORT:8080}

# JWT (IAM bounded context)
authorization.jwt.secret=TherapyConnectPlatformSecretKeyForJWT2026!
authorization.jwt.expiration.days=7
