# Production profile
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.initialization-fail-timeout=-1

server.port=${PORT:8080}

# JWT (IAM bounded context)
authorization.jwt.secret=${JWT_SECRET}
authorization.jwt.expiration.days=7
