# Development profile
spring.datasource.url=jdbc:postgresql://localhost:5432/therapyconnect_db
spring.datasource.username=postgres
spring.datasource.password=kevinedu@lex845189BBOY92

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

server.port=8080

# CORS for local Angular dev server
spring.web.cors.allowed-origins=http://localhost:4200
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
